Updated README.md with composer.json
EasyEngine/mailhog-command pull request #7
Opened 2018-09-13 07:52 UTC by sagarnasit

2018-09-14 15:30 UTC, mbtamuli requested changes

2018-09-14 15:30 UTC, mbtamuli commented on README.md
> +Commanad to enable disable mailhog for sites.
`Command to manage mailhog`

2018-09-14 15:30 UTC, mbtamuli commented on README.md
> +Enables/Disables admin-tools on a site.
`Manage admin-tools`

2018-09-17 06:13 UTC, sagarnasit commented
@mbtamuli Done with changes.

2018-09-17 12:36 UTC, mbtamuli approved these changes

2018-09-17 12:49 UTC, merged